# Generated by Django 5.1.7 on 2025-04-29 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_rename_change_points_stockdata_low_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockdata',
            old_name='turnover',
            new_name='turnover_rs_cr',
        ),
    ]
